name: Run Ansible Playbook

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
###S: Ansible {
      - name: Run playbook
        run: ansible-playbook --connection=local --inventory localhost, ./devops/ansible/playbooks/*yaml
###S: Ansible }
